<?php
namespace App\Services;

use App\Core\Database;
use Dompdf\{Dompdf, Options};
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PDO;

final class ReportGenerator
{
    public function generate(string $type,string $format,?int $municipalityId,?string $from,?string $to,string $generatedBy): string
    {
        $report=$this->data($type,$municipalityId,$from?:null,$to?:null,$generatedBy);$directory=BASE_PATH.'/storage/reports';if(!is_dir($directory)&&!mkdir($directory,0775,true)&&!is_dir($directory))throw new \RuntimeException('Report storage is unavailable');$filename=sprintf('%s_%s_%s.%s',$type,gmdate('Ymd_His'),bin2hex(random_bytes(4)),$format);$absolute=$directory.'/'.$filename;try{$format==='pdf'?$this->pdf($report,$absolute):$this->excel($report,$absolute);}catch(\Throwable $e){if(is_file($absolute))unlink($absolute);throw $e;}return 'storage/reports/'.$filename;
    }
    private function data(string $type,?int $mid,?string $from,?string $to,string $generatedBy): array
    {
        if($type==='evacuation_center')return $this->evacuationCenterData($mid,$from,$to,$generatedBy);
        $db=Database::connection();$scope='Province-wide';if($mid){$s=$db->prepare('SELECT municipality_name FROM municipalities WHERE id=? AND status="active"');$s->execute([$mid]);$scope=(string)$s->fetchColumn();if($scope==='')throw new \InvalidArgumentException('Invalid municipality');}$where=[];$values=[];
        if($type==='hazard'){$title='Hazard Report';$date='h.created_at';$where[]='h.status="active"';$sql='SELECT h.hazard_name "Hazard Name",REPLACE(h.hazard_type,"_"," ") "Hazard Type",h.risk_level "Risk Level",COALESCE(m.municipality_name,"Province-wide") Municipality,h.description Description,DATE_FORMAT(h.created_at,"%Y-%m-%d") "Created Date" FROM hazards h LEFT JOIN municipalities m ON m.id=h.municipality_id';$category='Hazard Type';$critical='Risk Level';$definitions=['Hazard Type'=>'Mapped hazard classification.','Risk Level'=>'Current operational risk assigned to the hazard.','Created Date'=>'Date the hazard record was created.'];$steps=['Review critical and high-risk areas with municipal DRRM offices.','Verify GeoJSON boundaries and update stale records.','Confirm evacuation resources cover the highest-risk areas.'];$caveat='Includes active hazard records only. Risk levels depend on submitted assessments and may not reflect current field conditions.';}
        elseif($type==='alert'){$title='Alert Report';$date='a.created_at';$where[]='a.status="sent"';$sql='SELECT a.title Title,REPLACE(a.alert_type,"_"," ") "Alert Type",a.alert_level "Alert Level",COALESCE(m.municipality_name,"Province-wide") Municipality,a.message Message,DATE_FORMAT(a.sent_at,"%Y-%m-%d %H:%i") "Sent At",u.fullname "Created By" FROM alerts a LEFT JOIN municipalities m ON m.id=a.municipality_id JOIN users u ON u.id=a.created_by';$category='Alert Type';$critical='Alert Level';$definitions=['Alert Type'=>'Operational category of the alert.','Alert Level'=>'Information, advisory, warning, or critical urgency.','Sent At'=>'Time the alert became visible to residents.'];$steps=['Review critical alerts for response follow-through.','Confirm targeting and resident receipt coverage.','Issue a new alert when correcting sent information.'];$caveat='Includes sent alerts only. Application history does not guarantee delivery through SMS, radio, or physical channels.';}
        else{$title='Historical Disaster Report';$date='d.date_occurred';$sql='SELECT d.title Title,d.disaster_type "Disaster Type",m.municipality_name Municipality,DATE_FORMAT(d.date_occurred,"%Y-%m-%d") "Date Occurred",d.casualties Casualties,d.damages Damages,d.description Description FROM historical_disasters d JOIN municipalities m ON m.id=d.municipality_id';$category='Disaster Type';$critical=null;$definitions=['Date Occurred'=>'Recorded date of the event.','Casualties'=>'Recorded number of casualties.','Damages'=>'Recorded monetary estimate in the configured local currency.'];$steps=['Validate high-impact records against official assessments.','Use recurring disaster types to prioritize mitigation.','Complete missing damage estimates before trend comparison.'];$caveat='Historical totals depend on entered post-disaster records. Damage estimates may use different methods and are not inflation-adjusted.';}
        $alias=$type==='hazard'?'h':($type==='alert'?'a':'d');if($mid){$where[]="$alias.municipality_id=?";$values[]=$mid;}if($from){$where[]="DATE($date)>=?";$values[]=$from;}if($to){$where[]="DATE($date)<=?";$values[]=$to;}if($where)$sql.=' WHERE '.implode(' AND ',$where);$sql.=" ORDER BY $date DESC LIMIT 10000";$s=$db->prepare($sql);$s->execute($values);$rows=$s->fetchAll(PDO::FETCH_ASSOC);$headers=$rows?array_keys($rows[0]):array_keys($this->emptyShape($type));$breakdown=[];$criticalCount=0;foreach($rows as $row){$label=ucwords((string)$row[$category]);$breakdown[$label]=($breakdown[$label]??0)+1;if($critical!==null&&strtolower((string)$row[$critical])==='critical')$criticalCount++;}arsort($breakdown);$period=($from||$to)?($from?:'earliest').' to '.($to?:'latest'):'All available dates';$top=$breakdown?array_key_first($breakdown).' ('.reset($breakdown).')':'No records';$impact=$type==='historical_disaster'?array_sum(array_column($rows,'Casualties')).' casualties and '.number_format(array_sum(array_map('floatval',array_column($rows,'Damages'))),2).' in recorded damages.':$criticalCount.' records are classified as critical.';return ['title'=>$title,'generated_at'=>date('F j, Y g:i A'),'generated_by'=>$generatedBy,'scope'=>$scope.' - '.$period,'summary'=>[count($rows).' records are included.','The largest category is '.$top.'.',$impact],'breakdown'=>$breakdown,'headers'=>$headers,'rows'=>$rows,'definitions'=>$definitions,'next_steps'=>$steps,'caveat'=>$caveat];
    }
    private function evacuationCenterData(?int $mid,?string $from,?string $to,string $generatedBy): array
    {
        $db=Database::connection();$scope='Province-wide';$where=['e.status<>"deleted"'];$values=[];
        if($mid){$statement=$db->prepare('SELECT municipality_name FROM municipalities WHERE id=? AND status="active"');$statement->execute([$mid]);$scope=(string)$statement->fetchColumn();$where[]='e.municipality_id=?';$values[]=$mid;}
        if($from){$where[]='DATE(e.created_at)>=?';$values[]=$from;}if($to){$where[]='DATE(e.created_at)<=?';$values[]=$to;}
        $sql='SELECT e.center_name "Center Name",m.municipality_name Municipality,e.address Address,e.contact_person "Contact Person",e.contact_number "Contact Number",e.capacity Capacity,REPLACE(e.status,"_"," ") Status,DATE_FORMAT(e.updated_at,"%Y-%m-%d") "Last Updated" FROM evacuation_centers e JOIN municipalities m ON m.id=e.municipality_id WHERE '.implode(' AND ',$where).' ORDER BY e.updated_at DESC LIMIT 10000';
        $statement=$db->prepare($sql);$statement->execute($values);$rows=$statement->fetchAll(PDO::FETCH_ASSOC);$breakdown=[];foreach($rows as $row){$label=ucwords((string)$row['Status']);$breakdown[$label]=($breakdown[$label]??0)+1;}arsort($breakdown);$period=($from||$to)?($from?:'earliest').' to '.($to?:'latest'):'All available dates';
        return ['title'=>'Evacuation Center Report','generated_at'=>date('F j, Y g:i A'),'generated_by'=>$generatedBy,'scope'=>$scope.' - '.$period,'summary'=>[count($rows).' evacuation centers are included.',number_format(array_sum(array_column($rows,'Capacity'))).' total listed capacity.','Operating status should be verified before deployment.'],'breakdown'=>$breakdown,'headers'=>$rows?array_keys($rows[0]):['Center Name','Municipality','Address','Contact Person','Contact Number','Capacity','Status','Last Updated'],'rows'=>$rows,'definitions'=>['Contact Person'=>'Primary facility contact or focal person.','Contact Number'=>'Phone number for the listed facility contact.','Capacity'=>'Maximum listed facility capacity.','Status'=>'Current reported operating condition.','Last Updated'=>'Most recent database update date.'],'next_steps'=>['Verify capacity and contact details with municipal teams.','Prioritize readiness checks for unavailable facilities.','Confirm accessible routes to each active center.'],'caveat'=>'Capacity and status are operational records and require field verification during an emergency.'];
    }
    private function pdf(array $r,string $path): void { $options=new Options();$options->set('isRemoteEnabled',false);$pdf=new Dompdf($options);$pdf->loadHtml($this->html($r),'UTF-8');$pdf->setPaper('A4','landscape');$pdf->render();file_put_contents($path,$pdf->output()); }
    private function excel(array $r,string $path): void
    {
        $book=new Spreadsheet();$summary=$book->getActiveSheet();$summary->setTitle('Executive Summary');$summary->setCellValue('A1',$r['title'])->mergeCells('A1:D1');$summary->getStyle('A1:D1')->getFont()->setBold(true)->setSize(18)->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color('FFFFFFFF'));$summary->getStyle('A1:D1')->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FF1E3A8A');$summary->fromArray([['Generated',$r['generated_at']],['Generated By',$r['generated_by']],['Scope',$r['scope']]],null,'A3');$summary->setCellValue('A7','Executive Summary');$summary->getStyle('A7')->getFont()->setBold(true)->setSize(14);$row=8;foreach($r['summary'] as $line){$summary->setCellValue("A$row",'- '.$line)->mergeCells("A$row:D$row");$row++;}$row+=2;$summary->setCellValue("A$row",'Breakdown');$summary->getStyle("A$row")->getFont()->setBold(true);$summary->fromArray(['Category','Count'],null,'A'.++$row);foreach($r['breakdown'] as $label=>$count)$summary->fromArray([$label,$count],null,'A'.++$row);$summary->getColumnDimension('A')->setWidth(44);$summary->getColumnDimension('B')->setWidth(24);
        $data=$book->createSheet();$data->setTitle('Report Data');$last=$this->columnLetter(count($r['headers']));$data->fromArray($r['headers'],null,'A1');$data->getStyle("A1:{$last}1")->getFont()->setBold(true)->setColor(new \PhpOffice\PhpSpreadsheet\Style\Color('FFFFFFFF'));$data->getStyle("A1:{$last}1")->getFill()->setFillType(Fill::FILL_SOLID)->getStartColor()->setARGB('FF334155');$row=2;foreach($r['rows'] as $values)$data->fromArray(array_values($values),null,'A'.$row++);$data->freezePane('A2');$data->setAutoFilter("A1:{$last}".max(1,$row-1));for($i=1;$i<=count($r['headers']);$i++)$data->getColumnDimension($this->columnLetter($i))->setAutoSize(true);
        $defs=$book->createSheet();$defs->setTitle('Definitions');$defs->fromArray(['Field','Definition'],null,'A1');$row=2;foreach($r['definitions'] as $field=>$definition)$defs->fromArray([$field,$definition],null,'A'.$row++);$defs->getStyle('A1:B1')->getFont()->setBold(true);$defs->getColumnDimension('A')->setWidth(30);$defs->getColumnDimension('B')->setWidth(80);$defs->getStyle('B:B')->getAlignment()->setWrapText(true);$book->setActiveSheetIndex(0);(new Xlsx($book))->save($path);$book->disconnectWorksheets();
    }
    private function html(array $r): string
    {
        $e=fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES,'UTF-8');$summary='';foreach($r['summary'] as $line)$summary.='<li>'.$e($line).'</li>';$bars='';$max=max([1,...array_values($r['breakdown'])]);foreach($r['breakdown'] as $label=>$count)$bars.='<div class="bar"><span>'.$e($label).'</span><i style="width:'.max(1,round($count/$max*100)).'%"></i><b>'.$count.'</b></div>';$head='';foreach($r['headers'] as $h)$head.='<th>'.$e($h).'</th>';$body='';foreach($r['rows'] as $row){$body.='<tr>';foreach($row as $value)$body.='<td>'.$e($value).'</td>';$body.='</tr>';}$next='';foreach($r['next_steps'] as $step)$next.='<li>'.$e($step).'</li>';return '<html><head><meta charset="utf-8"><style>@page{margin:28px}body{font:10px DejaVu Sans;color:#1e293b}h1{color:#1e3a8a;font-size:22px}h2{font-size:14px;border-bottom:1px solid #cbd5e1;padding-bottom:5px;margin-top:18px}.meta{color:#64748b}.summary{background:#eff6ff;border-left:4px solid #2563eb;padding:8px 12px}.bar{margin:6px 0}.bar span{display:inline-block;width:145px}.bar i{display:inline-block;background:#2563eb;height:10px;max-width:340px}.bar b{margin-left:8px}table{border-collapse:collapse;width:100%;font-size:8px}th{background:#334155;color:#fff}th,td{border:1px solid #cbd5e1;padding:5px}.caveat{background:#fffbeb;border:1px solid #fde68a;padding:8px}</style></head><body><h1>'.$e($r['title']).'</h1><p class="meta">Generated '.$e($r['generated_at']).' &middot; '.$e($r['scope']).'</p><h2>Executive Summary</h2><div class="summary"><ul>'.$summary.'</ul></div><h2>Key Findings</h2><p>Category distribution supports operational prioritization.</p>'.$bars.'<h2>Detailed Evidence</h2><table><tr>'.$head.'</tr>'.$body.'</table><h2>Recommended Next Steps</h2><ol>'.$next.'</ol><h2>Further Questions</h2><p>Would missing, unverified, or archived records materially change the operational picture?</p><h2>Caveats and Assumptions</h2><p class="caveat">'.$e($r['caveat']).'</p></body></html>';
    }
    private function emptyShape(string $type): array { return $type==='hazard'?['Hazard Name'=>'','Hazard Type'=>'','Risk Level'=>'','Municipality'=>'','Description'=>'','Created Date'=>'']:($type==='alert'?['Title'=>'','Alert Type'=>'','Alert Level'=>'','Municipality'=>'','Message'=>'','Sent At'=>'','Created By'=>'']:['Title'=>'','Disaster Type'=>'','Municipality'=>'','Date Occurred'=>'','Casualties'=>'','Damages'=>'','Description'=>'']); }
    private function columnLetter(int $number): string { $letter='';while($number>0){$number--;$letter=chr(65+$number%26).$letter;$number=intdiv($number,26);}return $letter; }
}
